"""
=============================================================================
Agro-Spectra | MODULE 2: PHYSICS-INFORMED GYMNASIUM ENVIRONMENT
File        : agro_env.py
Description : AgroEnv — a custom gymnasium.Env that simulates daily
              soil moisture and nitrogen dynamics on a 30-day farm episode.
              Climate state is sampled from mock_farm_data.csv (generated by
              data_generator.py). Falls back to rule-based sampling if the
              CSV is not found.

OpenEnv Compatibility:
    The environment follows the full gymnasium API contract, making it
    directly wrappable by Meta's OpenEnv framework.
=============================================================================
Observation Space : Box(4,)  — [Moisture, Nitrogen, Temperature, Rainfall]
                              All values normalised to [0.0, 1.0]
Action Space      : Discrete(3)
                      0 → Do Nothing
                      1 → Irrigate      (+15 moisture, -1 reward)
                      2 → Fertilize     (+20 nitrogen,  -2 reward)
Episode Length    : 30 steps (truncated at step_count == 30)
=============================================================================
"""

import os
import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces


# ---------------------------------------------------------------------------
# Climate normalisation constants (used to scale obs to [0, 1])
# ---------------------------------------------------------------------------
TEMP_MIN  = 15.0    # °C — coldest possible day (winter lower bound)
TEMP_MAX  = 45.0    # °C — hottest possible day  (summer upper bound)
RAIN_MIN  = 0.0     # mm
RAIN_MAX  = 50.0    # mm — monsoon upper bound

# Soil variable physical bounds
MOISTURE_MIN = 0.0
MOISTURE_MAX = 100.0
NITROGEN_MIN = 0.0
NITROGEN_MAX = 100.0

# Ideal growing ranges (used in reward computation)
MOISTURE_LOW, MOISTURE_HIGH = 40.0, 60.0
NITROGEN_LOW, NITROGEN_HIGH = 50.0, 70.0

# Episode length (days per episode)
MAX_STEPS = 30

# Path to the climate CSV generated by data_generator.py
_DEFAULT_CSV_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "mock_farm_data.csv"
)


# ---------------------------------------------------------------------------
# Helper: fallback climate sampler (no CSV required)
# ---------------------------------------------------------------------------
def _sample_climate_from_rules(rng: np.random.Generator) -> tuple[float, float]:
    """
    Rule-based climate sampler mimicking the seasonal distributions in
    data_generator.py. Used when mock_farm_data.csv is unavailable.

    Returns
    -------
    (temperature_C, rainfall_mm) : tuple of floats
    """
    # Randomly pick a season with weights proportional to day counts
    season = rng.choice(["summer", "monsoon", "winter"],
                        p=[90/365, 101/365, 174/365])

    if season == "summer":
        temp = rng.uniform(30.0, 45.0)
        rain = rng.uniform(1.0, 5.0) if rng.random() < 0.07 else 0.0
    elif season == "monsoon":
        temp = rng.uniform(25.0, 35.0)
        rain = rng.uniform(10.0, 50.0) if rng.random() < 0.75 else 0.0
    else:   # winter
        temp = rng.uniform(15.0, 25.0)
        rain = rng.uniform(1.0, 5.0) if rng.random() < 0.07 else 0.0

    return float(temp), float(rain)


# ---------------------------------------------------------------------------
# AgroEnv
# ---------------------------------------------------------------------------
class AgroEnv(gym.Env):
    """
    Physics-informed precision agriculture environment.

    The agent controls irrigation and fertilization on a simulated 30-day
    growing window. The goal is to keep soil moisture (40–60) and nitrogen
    (50–70) within optimal bands while minimising chemical runoff penalties.

    Parameters
    ----------
    csv_path : str, optional
        Path to mock_farm_data.csv. Defaults to the file location relative
        to this script. If the file is absent, rule-based fallback sampling
        is used automatically.
    seed : int, optional
        Master seed for reproducibility.

    Attributes
    ----------
    observation_space : spaces.Box
        4-dimensional float32 box, values in [0.0, 1.0].
    action_space : spaces.Discrete
        Three discrete actions: 0=Do Nothing, 1=Irrigate, 2=Fertilize.
    """

    metadata = {"render_modes": ["human"], "render_fps": 1}

    # Human-readable action labels (useful for logging)
    ACTION_LABELS = {0: "Do Nothing", 1: "Irrigate", 2: "Fertilize"}

    def __init__(self, csv_path: str = _DEFAULT_CSV_PATH, seed: int = None):
        super().__init__()

        # ---- Spaces --------------------------------------------------------
        self.observation_space = spaces.Box(
            low=0.0, high=1.0, shape=(4,), dtype=np.float32
        )
        self.action_space = spaces.Discrete(3)

        # ---- Climate data --------------------------------------------------
        self._csv_path    = csv_path
        self._climate_df  = None   # loaded lazily in reset()
        self._use_csv     = False  # toggled once CSV is successfully loaded

        # ---- RNG -----------------------------------------------------------
        self._master_seed = seed
        self._rng = np.random.default_rng(seed)

        # ---- State (initialised in reset) ----------------------------------
        self.moisture   : float = 50.0
        self.nitrogen   : float = 50.0
        self.step_count : int   = 0

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _load_csv(self) -> None:
        """Load mock_farm_data.csv; set flag if successful."""
        if os.path.exists(self._csv_path):
            self._climate_df = pd.read_csv(self._csv_path)
            self._use_csv    = True
        else:
            print(
                f"[AgroEnv] WARNING: '{self._csv_path}' not found. "
                "Falling back to rule-based climate sampling."
            )
            self._use_csv = False

    def _sample_climate(self) -> tuple[float, float]:
        """
        Sample today's temperature and rainfall.

        Picks a random row from the CSV when available; otherwise delegates
        to the rule-based sampler.

        Returns
        -------
        (temperature_C, rainfall_mm)
        """
        if self._use_csv:
            row  = self._climate_df.sample(n=1, random_state=self._rng.integers(0, 2**31)).iloc[0]
            temp = float(row["Temperature_C"])
            rain = float(row["Rainfall_mm"])
        else:
            temp, rain = _sample_climate_from_rules(self._rng)

        return temp, rain

    @staticmethod
    def _normalise(value: float, lo: float, hi: float) -> float:
        """Min-max normalise `value` from [lo, hi] to [0.0, 1.0]."""
        return float(np.clip((value - lo) / (hi - lo), 0.0, 1.0))

    def _build_observation(self, temp: float, rain: float) -> np.ndarray:
        """
        Compose the 4-element normalised observation vector.

        Returns
        -------
        np.ndarray shape (4,) dtype float32
            [norm_moisture, norm_nitrogen, norm_temp, norm_rain]
        """
        return np.array([
            self._normalise(self.moisture, MOISTURE_MIN, MOISTURE_MAX),
            self._normalise(self.nitrogen, NITROGEN_MIN, NITROGEN_MAX),
            self._normalise(temp,          TEMP_MIN,     TEMP_MAX),
            self._normalise(rain,          RAIN_MIN,     RAIN_MAX),
        ], dtype=np.float32)

    # ------------------------------------------------------------------
    # Core Gymnasium API
    # ------------------------------------------------------------------

    def reset(
        self,
        *,
        seed: int = None,
        options: dict = None,
    ) -> tuple[np.ndarray, dict]:
        """
        Reset the environment to its initial state for a new episode.

        Parameters
        ----------
        seed : int, optional
            Override the master seed for this episode.
        options : dict, optional
            Reserved for future use (ignored).

        Returns
        -------
        observation : np.ndarray
            Initial normalised state vector.
        info : dict
            Auxiliary diagnostic data.
        """
        super().reset(seed=seed)

        # Re-seed RNG if an explicit seed is provided
        if seed is not None:
            self._rng = np.random.default_rng(seed)

        # Lazily load climate data on first reset
        if self._climate_df is None:
            self._load_csv()

        # Initialise soil state at planting baseline
        self.moisture   = 50.0   # moderate initial moisture (%)
        self.nitrogen   = 50.0   # moderate initial nitrogen  (kg/ha equivalent)
        self.step_count = 0

        # Sample today's climate to form the first observation
        temp, rain = self._sample_climate()
        obs = self._build_observation(temp, rain)

        info = {
            "day"        : self.step_count,
            "moisture"   : self.moisture,
            "nitrogen"   : self.nitrogen,
            "temperature": temp,
            "rainfall"   : rain,
        }
        return obs, info

    def step(self, action: int) -> tuple[np.ndarray, float, bool, bool, dict]:
        """
        Advance the environment by one day.

        Physics chain (raw, un-normalised values):
        ┌─────────────────────────────────────────────────────────────────┐
        │ 1. Evapotranspiration  = Temperature × 0.5                      │
        │ 2. Next Moisture       = Moisture + Rainfall                     │
        │                        + (15 if Irrigate else 0)               │
        │                        - Evapotranspiration                     │
        │ 3. Leaching            = 5 if Moisture > 80 else 0              │
        │ 4. Next Nitrogen       = Nitrogen + (20 if Fertilize else 0)    │
        │                        - 2 (plant uptake)                       │
        │                        - Leaching                               │
        │ → Clamp both to [0, 100]                                        │
        └─────────────────────────────────────────────────────────────────┘

        Reward structure:
        ┌─────────────────────────────────────────────────────────────────┐
        │  +5   Base reward if 40 ≤ Moisture ≤ 60 AND 50 ≤ N ≤ 70       │
        │  -1   Irrigation cost  (action == 1)                            │
        │  -2   Fertilize cost   (action == 2)                            │
        │  -10  Chemical runoff  (Nitrogen > 90)                          │
        │  -5   Drought penalty  (Moisture < 20)                          │
        └─────────────────────────────────────────────────────────────────┘

        Parameters
        ----------
        action : int  ∈ {0, 1, 2}

        Returns
        -------
        observation : np.ndarray   — normalised state (4,)
        reward      : float
        terminated  : bool         — always False (no natural terminal state)
        truncated   : bool         — True when step_count ≥ MAX_STEPS
        info        : dict         — raw (un-normalised) diagnostic values
        """
        # Validate action
        assert self.action_space.contains(action), \
            f"Invalid action {action}. Must be in {{0, 1, 2}}."

        # ---- Sample today's climate ----------------------------------------
        temp, rain = self._sample_climate()

        # ---- Physics: Moisture update (raw) --------------------------------
        evapotranspiration = temp * 0.5
        irrigation_input   = 15.0 if action == 1 else 0.0

        next_moisture = (
            self.moisture
            + rain
            + irrigation_input
            - evapotranspiration
        )

        # ---- Physics: Nitrogen update (raw) on CURRENT moisture ------------
        leaching          = 5.0 if self.moisture > 80.0 else 0.0
        fertilizer_input  = 20.0 if action == 2 else 0.0
        plant_uptake      = 2.0

        next_nitrogen = (
            self.nitrogen
            + fertilizer_input
            - plant_uptake
            - leaching
        )

        # ---- Clamp to physical bounds --------------------------------------
        next_moisture = float(np.clip(next_moisture, MOISTURE_MIN, MOISTURE_MAX))
        next_nitrogen = float(np.clip(next_nitrogen, NITROGEN_MIN, NITROGEN_MAX))

        # ---- Commit new state ---------------------------------------------
        self.moisture = next_moisture
        self.nitrogen = next_nitrogen
        self.step_count += 1

        # ---- Reward computation -------------------------------------------
        reward = 0.0

        # Base reward: both variables in optimal range
        in_optimal_band = (
            MOISTURE_LOW <= self.moisture <= MOISTURE_HIGH
            and NITROGEN_LOW <= self.nitrogen <= NITROGEN_HIGH
        )
        if in_optimal_band:
            reward += 5.0

        # Action costs
        if action == 1:
            reward -= 1.0   # irrigation cost
        elif action == 2:
            reward -= 2.0   # fertilizer cost

        # Environmental penalty: nitrogen runoff risk
        if self.nitrogen > 90.0:
            reward -= 10.0

        # Drought penalty
        if self.moisture < 20.0:
            reward -= 5.0

        # ---- Termination check --------------------------------------------
        terminated = False                      # no absorbing terminal state
        truncated  = self.step_count >= MAX_STEPS

        # ---- Build observation --------------------------------------------
        obs = self._build_observation(temp, rain)

        info = {
            "day"              : self.step_count,
            "action_label"     : self.ACTION_LABELS[action],
            "moisture"         : self.moisture,
            "nitrogen"         : self.nitrogen,
            "temperature"      : temp,
            "rainfall"         : rain,
            "evapotranspiration": evapotranspiration,
            "leaching"         : leaching,
            "in_optimal_band"  : in_optimal_band,
        }

        return obs, reward, terminated, truncated, info

    def render(self) -> None:
        """
        Render the current state to stdout.

        Prints a concise summary of the raw soil variables and day count.
        (render_mode='human' only; no visual output.)
        """
        print(
            f"  Day {self.step_count:>2d}/30 | "
            f"Moisture: {self.moisture:5.1f}% | "
            f"Nitrogen: {self.nitrogen:5.1f} kg/ha"
        )

    def close(self) -> None:
        """Clean up resources (no-op for this environment)."""
        pass


# ---------------------------------------------------------------------------
# Quick smoke-test — run this file directly to verify the environment works
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("=" * 60)
    print("  Agro-Spectra | AgroEnv Smoke Test")
    print("=" * 60)

    env = AgroEnv(seed=0)
    obs, info = env.reset()
    print(f"\nInitial observation : {obs}")
    print(f"Initial info        : {info}\n")

    total_reward = 0.0
    for _ in range(MAX_STEPS):
        action = env.action_space.sample()
        obs, reward, terminated, truncated, info = env.step(action)
        env.render()
        total_reward += reward
        if terminated or truncated:
            break

    print(f"\nEpisode finished — Total Reward: {total_reward:.2f}")
    env.close()
